site_name: hatchpoc
site_url: https://github.com/bossjones/hatchpoc
site_author: Malcolm Jones
site_description: Simple library for me to test out playing with hatchling

repo_name: bossjones/hatchpoc
repo_url: https://github.com/bossjones/hatchpoc

copyright: Copyright (c) 2023-present Malcolm Jones <bossjones@theblacktonystark.com>

theme:
  name: material
  palette:
  - scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  plugins:
  - search
  - awesome-pages
  - include-markdown

markdown_extensions:
- codehilite
- admonition
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.details
- pymdownx.magiclink
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.superfences

plugins:
- search:
- git-revision-date-localized:
    type: timeago
    enable_creation_date: true
- mkdocstrings:


extra:
  social:
  - icon: fontawesome/brands/python
    link: https://pypi.org/project/hatchpoc/
  - icon: fontawesome/brands/github
    link: https://github.com/bossjones
    # - icon: fontawesome/brands/twitter
    #   link: https://twitter.com/REPLACE_TWITTER_USERNAME
    # - icon: fontawesome/brands/linkedin
    #   link: https://www.linkedin.com/in/REPLACE_LINKEDIN_USERNAME/

nav:
- Home: index.md
- License: license.md
