#!/usr/bin/env bash

code --install-extension 29ways.boss
code --install-extension adamhartford.vscode-base64
code --install-extension akamud.vscode-theme-onedark
code --install-extension albymor.increment-selection
code --install-extension alefragnani.project-manager
code --install-extension alexcvzz.vscode-sqlite
code --install-extension Artymaury.template-finder
code --install-extension Asuka.insertnumbers
code --install-extension awarest.awarest-align
code --install-extension bdavs.expect
code --install-extension bibhasdn.unique-lines
code --install-extension brunomartens.bma-coverage
code --install-extension bungcip.better-toml
code --install-extension caarlos0.language-prometheus
code --install-extension christian-kohler.path-intellisense
code --install-extension codezombiech.gitignore
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension coolbear.systemd-unit-file
code --install-extension cweijan.vscode-office
code --install-extension cybai.yaml-key-viewer
code --install-extension dariofuzinato.vscode-download-file
code --install-extension darkriszty.markdown-table-prettify
code --install-extension devine-davies.make-hidden
code --install-extension diegofn.vscode-uriencode
code --install-extension donjayamanne.createuniqueid
code --install-extension donjayamanne.git-extension-pack
code --install-extension donjayamanne.githistory
code --install-extension donjayamanne.listFiles
code --install-extension DotJoshJohnson.xml
code --install-extension dracula-theme.theme-dracula
code --install-extension drphrozen.escaping-characters
code --install-extension eamodio.gitlens
code --install-extension earshinov.sort-lines-by-selection
code --install-extension EditorConfig.EditorConfig
code --install-extension emilast.LogFileHighlighter
code --install-extension emmanuelbeziat.vscode-great-icons
code --install-extension enochc.copy-relative-path
code --install-extension Equinusocio.vsc-community-material-theme
code --install-extension Equinusocio.vsc-material-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension eriklynd.json-tools
code --install-extension erikphansen.vscode-toggle-column-selection
code --install-extension esbenp.prettier-vscode
code --install-extension ExodiusStudios.comment-anchors
code --install-extension fbaligand.vscode-logstash-editor
code --install-extension felipecaputo.git-project-manager
code --install-extension ferdinandsilva.vsc-figlet
code --install-extension file-icons.file-icons
code --install-extension flesler.url-encode
code --install-extension formulahendry.code-runner
code --install-extension formulahendry.terminal
code --install-extension fosshaas.fontsize-shortcuts
code --install-extension foxundermoon.shell-format
code --install-extension freakypie.code-python-isort
code --install-extension frhtylcn.pythonsnippets
code --install-extension geddski.macros
code --install-extension ginfuru.ginfuru-vscode-jekyll-syntax
code --install-extension ginfuru.vscode-jekyll-snippets
code --install-extension GitHub.github-vscode-theme
code --install-extension GitHub.vscode-pull-request-github
code --install-extension GlenBuktenica.unicode-substitutions
code --install-extension graykode.ai-docstring
code --install-extension hangxingliu.vscode-nginx-conf-hint
code --install-extension hashicorp.terraform
code --install-extension helixquar.asciidecorator
code --install-extension henriiik.vscode-sort
code --install-extension heyimfuzz.banner-comments
code --install-extension himanoa.Python-autopep8
code --install-extension hnw.vscode-auto-open-markdown-preview
code --install-extension HookyQR.beautify
code --install-extension hoovercj.vscode-power-mode
code --install-extension idleberg.applescript
code --install-extension ipedrazas.kubernetes-snippets
code --install-extension j-zeppenfeld.tab-indent-space-align
code --install-extension jakebathman.nginx-log-highlighter
code --install-extension janisdd.vscode-edit-csv
code --install-extension jetmartin.bats
code --install-extension jiejie.Lua-Nginx-Snippets
code --install-extension jinhyuk.replace-curly-quotes
code --install-extension jinsihou.diff-tool
code --install-extension jmviz.quote-list
code --install-extension johnpapa.vscode-peacock
code --install-extension johnpapa.winteriscoming
code --install-extension joshuapoehls.json-escaper
code --install-extension jtcontreras90.yaml-path-extractor
code --install-extension juanmnl.vscode-theme-hydra
code --install-extension KevinRose.vsc-python-indent
code --install-extension kleber-swf.ocean-dark-extended
code --install-extension L13RARY.l13-diff
code --install-extension lextudio.restructuredtext
code --install-extension luggage66.AWK
code --install-extension lunuan.kubernetes-templates
code --install-extension mads-hartmann.bash-ide-vscode
code --install-extension maelvalais.autoconf
code --install-extension malmaud.tmux
code --install-extension marcostazi.VS-code-vagrantfile
code --install-extension mblode.pretty-formatter
code --install-extension mdickin.markdown-shortcuts
code --install-extension mechatroner.rainbow-csv
code --install-extension mgesbert.python-path
code --install-extension milovidov.escape-quotes
code --install-extension mohsen1.prettify-json
code --install-extension mousavian.ssh-config-syntax-highlighter
code --install-extension MrAnno.syslog-ng
code --install-extension ms-azuretools.vscode-azureterraform
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-python.black-formatter
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode.azure-account
code --install-extension ms-vscode.live-server
code --install-extension ms-vscode.makefile-tools
code --install-extension ms-vscode.sublime-keybindings
code --install-extension msysyamamoto.vscode-fluentd
code --install-extension narsenico.vscode-progressive-increment
code --install-extension Naturalclar.workspace-settings-json
code --install-extension naumovs.color-highlight
code --install-extension nemesv.copy-file-name
code --install-extension nidu.copy-json-path
code --install-extension njpwerner.autodocstring
code --install-extension njqdev.vscode-python-typehint
code --install-extension octref.vscode-json-transform
code --install-extension oderwat.indent-rainbow
code --install-extension PascalReitermann93.vscode-yaml-sort
code --install-extension pepri.subtitles-editor
code --install-extension phplasma.csv-to-table
code --install-extension pnp.polacode
code --install-extension rafaelmaiolla.diff
code --install-extension rafaelmaiolla.remote-vscode
code --install-extension redhat.vscode-commons
code --install-extension redhat.vscode-yaml
code --install-extension Remisa.shellman
code --install-extension richie5um2.vscode-sort-json
code --install-extension richie5um2.vscode-statusbar-json-path
code --install-extension rido3.wordcount
code --install-extension RobbOwen.synthwave-vscode
code --install-extension RoscoP.ActiveFileInStatusBar
code --install-extension rpinski.shebang-snippets
code --install-extension Rubymaniac.vscode-paste-and-indent
code --install-extension rupisaini.vscode-ansible-linter
code --install-extension ryanluker.vscode-coverage-gutters
code --install-extension ryu1kn.partial-diff
code --install-extension sadesyllas.explorer-excluded-files
code --install-extension samuelcolvin.jinjahtml
code --install-extension sdras.night-owl
code --install-extension secsamdev.grok
code --install-extension sgryjp.vscode-stable-sort
code --install-extension shanoor.vscode-nginx
code --install-extension sharat.vscode-brewfile
code --install-extension Shinotatwu-DS.file-tree-generator
code --install-extension sleistner.vscode-fileutils
code --install-extension telesoho.vscode-markdown-paste-image
code --install-extension thegtproject.hoverhex
code --install-extension Thog.vscode-asl
code --install-extension timonwong.ansible-autocomplete
code --install-extension timonwong.shellcheck
code --install-extension tushortz.python-extended-snippets
code --install-extension tuxtina.json2yaml
code --install-extension Tyriar.sort-lines
code --install-extension VisualStudioExptTeam.intellicode-api-usage-examples
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscode-icons-team.vscode-icons
code --install-extension waderyan.gitblame
code --install-extension Wattenberger.footsteps
code --install-extension wayou.vscode-todo-highlight
code --install-extension wesbos.theme-cobalt2
code --install-extension whizkydee.material-palenight-theme
code --install-extension wholroyd.jinja
code --install-extension wmaurer.change-case
code --install-extension xrc-inc.jsonnet-formatter
code --install-extension yzhang.markdown-all-in-one
code --install-extension ZainChen.json
code --install-extension Zarel.sublime-commands
code --install-extension zengxingxin.sort-js-object-keys
code --install-extension ziyasal.vscode-open-in-github
