name: build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  # use cibuildwheel if project is not pure-python: https://github.com/pypa/cibuildwheel
  dist:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      # actions: read|write|none
      # checks: read|write|none
      contents: write
      # deployments: read|write|none
      # id-token: read|write|none
      # issues: read|write|none
      # discussions: read|write|none
      packages: write
      # pages: read|write|none
      # pull-requests: read|write|none
      # repository-projects: read|write|none
      # security-events: read|write|none
      # statuses: read|write|none

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - uses: syphar/restore-virtualenv@v1
      - run: pip install '.[build]'
      - run: python -m build
      - uses: actions/upload-artifact@v3
        with:
          path: dist/*
