name: dependencies

on:
  schedule:
  - cron: "0 9 * * 1-5"
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - main

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0


    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - uses: syphar/restore-virtualenv@v1
    - run: pip install --requirement=requirements.txt '.[dev]'

      # skip some dependencies
    - run: pip uninstall --yes setuptools
